spring:
  datasource:
    url: 'jdbc:h2:mem:test'
    username: ''
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        SQL: debug